### ISSUE TITLE
made this for you

### ISSUE THREAD

**Issue by codingdudecom** [CentauriSoldier/Dox#2]
hi,

I remade your logo image using [Mockofun](https://www.mockofun.com/) and this is what I got:
![DOX logo](https://i.imgur.com/AsEdzFh.jpeg)

if you like it you can use it in your description. The only thing I ask is to place a link back to MockoFun, thanks!

**Comment by CentauriSoldier** [comment]
Oh nice, Thanks! Very lovely, I'll add it this weekend probably.
