### ISSUE TITLE
[ISSUE] util.lua cannot load correctly

### ISSUE THREAD

**Issue by alejandro-alzate** [CentauriSoldier/Dox#3]
It throws this when required:
`lua: ./dox/util.lua:41: attempt to index global 'Dialog' (a nil value)`

this is where it takes me:
`./dox/util.lua`
```lua

--[[!
@module dox.util
@func dox.util.getOSType
@desc Determines the operating system type the end-user if running.
@ret sOSType string returns 'windows' if it is a Windows systems and 'unix' if it a unix-based system.
!]]
function dox.util.getOSType()
	return sOSType;
end

--The offender is this:
local p = Dialog.Message;

function dox.util.getProcessList(sDir, bRecurse, tFiles)
	local tRet = type(tFiles) == "table" and tFiles or {};
	--TODO finish the unix commands
	--setup the commands
	local sGetFilesCommand 	= (_ == "\\") and	('dir "'..sDir..'\\*.*" /b /a-d'):gsub("\\\\", "\\") 	or ('find '..sDir.."/"..'-maxdepth 1 ! –type d'):gsub("//", "/");
	local sGetDirsCommand 	= (_ == "\\") and	('dir "'..sDir..'\\*.*" /b /d'):gsub("\\\\", "\\") 		or ("ls -a -d /*"):gsub("//", "/");
```

It is something in my end? i was trying to do a .sublime-build file to automatically run it:
`Dox: Create docs.sublime-build`
```json
{
	"shell_cmd": "mkdir -p $project_path/doc; lua mkdocs.lua $project_path",
	"shell": true,
	"working_dir": "$project_path",
}
```

`./mkdocs.lua`
```lua
local projectPath = {...}
require("dox.dox")
dox.processDir(projectPath, "doc")
```

this is the complete error:
```
lua: ./dox/util.lua:41: attempt to index global 'Dialog' (a nil value)
stack traceback:
	./dox/util.lua:41: in main chunk
	[C]: in function 'require'
```
is it because i'm using the version provided by my package manager?
or can it be the presence of luarocks on my machine?
`lua -v`
```
alejandro@mint:~$ lua -v
Lua 5.1.5  Copyright (C) 1994-2012 Lua.org, PUC-Rio
```
`luarocks --version`
```
alejandro@mint:~$ luarocks --version
/usr/bin/luarocks 3.8.0
LuaRocks main command-line interface
```
When lua loads code it isn't supposed to get rid of the comments before compiling on the fly?
What are the limitations to do just `alejandro@mint~project/$ lua dox/dox.lua .`?
I could may help to make it self contained, but don't know where even the Dialog thing is defined

**Comment by CentauriSoldier** [comment]
Thanks for the report. Sorry for the late reply, didn't see it until tonight.
Issue fixed. Please let me know if there is anything else.

**Comment by CentauriSoldier** [comment]
Thanks for the report. Sorry for the late reply, didn't see it until tonight.
Issue fixed. Please let me know if there is anything else.

**Comment by alejandro-alzate** [comment]
Don't worry, everybody has a live to deal with am i right?

**Comment by CentauriSoldier** [comment]
So true. Wish I had more time to code but six day work weeks cut into my fun time.

**Comment by alejandro-alzate** [comment]
Quite concerning the modern age with its overtime work hours and burn-out culture, hope you find a better work.
> Work on what you love and you will not work a single day of your life.

now with that aside what made it break? you don't have to respond me immediately or at all, just curious.

**Comment by CentauriSoldier** [comment]
Thanks, I hope so too.
The issue was that the **_Dialog.Message_** function was used in testing in AutoPlay Media Studio and that function is native to AMS, not Lua. I just forgot to remove it after testing.

**Comment by alejandro-alzate** [comment]
Oh I was losing my mind when i tried to find Dialog to debug it myself.
I mean i thought i downloaded the thing wrong, i read the readme like 9 times.
I was losing it, then i went to here to post this.
At least was a quick fix.
And a funny moment for posterity.
